apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: f47tf7o4w-nodejs-gitops
  description: This is GitOps manifest for f47tf7o4w-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: f47tf7o4w-nodejs
    janus-idp.io/tekton: f47tf7o4w-nodejs 
    backstage.io/kubernetes-id: f47tf7o4w-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:f47tf7o4w-nodejs
